# -*- coding: utf-8 -*-
lines = open("src/App.jsx", encoding="utf-8").readlines()

new_func = (
    "  function autoPlaceLights() {\n"
    "    if (!activeFixture) {\n"
    "      showToast(\"Please select a fixture from the library first\")\n"
    "      return\n"
    "    }\n"
    "    const W = roomWidth / 1000\n"
    "    const H = roomHeight / 1000\n"
    "    const area = W * H\n"
    "    if (area <= 0) { showToast(\"Please set room dimensions first\"); return }\n"
    "    const variants = activeFixture.variants ?? []\n"
    "    const midVariant = variants[Math.floor(variants.length / 2)] ?? {}\n"
    "    const fixWatt   = midVariant.watt      ?? activeFixture.watt      ?? 12\n"
    "    const fixLumens = midVariant.lumens    ?? activeFixture.lumens    ?? (fixWatt * 90)\n"
    "    const fixBeam   = midVariant.beamAngle ?? activeFixture.beamAngle ?? 36\n"
    "    const targetLuxVal = Number(room.targetLux) || 300\n"
    "    const UF = uf ?? 0.75\n"
    "    const MF = 0.80\n"
    "    const needed = Math.ceil((targetLuxVal * area) / (fixLumens * UF * MF))\n"
    "    const count  = Math.min(needed, 36)\n"
    "    const cols = Math.max(1, Math.round(Math.sqrt(count * (W / H))))\n"
    "    const rows = Math.ceil(count / cols)\n"
    "    const SCALE     = Math.min((CANVAS_W - 260) / roomWidth, (CANVAS_H - 220) / roomHeight)\n"
    "    const useDrawn  = roomOffsetX != null && drawnWidthPx != null\n"
    "    const ROOM_PX_W = useDrawn ? drawnWidthPx  : roomWidth  * SCALE\n"
    "    const ROOM_PX_H = useDrawn ? drawnHeightPx : roomHeight * SCALE\n"
    "    const ROOM_X    = roomOffsetX != null ? roomOffsetX : 20\n"
    "    const ROOM_Y    = roomOffsetY != null ? roomOffsetY : 30\n"
    "    const pxPerMm   = useDrawn ? drawnWidthPx / roomWidth : SCALE\n"
    "    const wallOffPx = 500 * pxPerMm\n"
    "    const usableW   = ROOM_PX_W - wallOffPx * 2\n"
    "    const usableH   = ROOM_PX_H - wallOffPx * 2\n"
    "    const spX       = cols > 1 ? usableW / (cols - 1) : 0\n"
    "    const spY       = rows > 1 ? usableH / (rows - 1) : 0\n"
    "    const generated = []\n"
    "    let ts = Date.now()\n"
    "    for (let r = 0; r < rows; r++) {\n"
    "      for (let c = 0; c < cols; c++) {\n"
    "        const px = cols > 1 ? ROOM_X + wallOffPx + c * spX : ROOM_X + ROOM_PX_W / 2\n"
    "        const py = rows > 1 ? ROOM_Y + wallOffPx + r * spY : ROOM_Y + ROOM_PX_H / 2\n"
    "        const light = makeLight(ts++, Math.round(px), Math.round(py), activeFixture, fixLumens)\n"
    "        light.watt = fixWatt\n"
    "        light.lumens = fixLumens\n"
    "        light.beamAngle = fixBeam\n"
    "        generated.push(light)\n"
    "      }\n"
    "    }\n"
    "    const achievedLux = Math.round((generated.length * fixLumens * UF * MF) / area)\n"
    "    patchActiveRoom(r => ({ lights: [...r.lights, ...generated] }))\n"
    "    showToast(`Placed ${generated.length} fixtures - ${achievedLux} lux`)\n"
    "  }\n"
    "\n"
)

new_lines = lines[:970] + [new_func] + lines[1095:]
open("src/App.jsx", "w", encoding="utf-8").write("".join(new_lines))
print("Done. New function written.")
