// ─────────────────────────────────────────────────────────────
// WATTAGE COLOR BANDS
// ─────────────────────────────────────────────────────────────
export function getWattageColor(watts) {
  if (watts <= 10)  return { hex: '#4caf50', name: 'green' }
  if (watts <= 20)  return { hex: '#2196f3', name: 'blue' }
  if (watts <= 36)  return { hex: '#d4a843', name: 'gold' }
  if (watts <= 75)  return { hex: '#ff9800', name: 'orange' }
  if (watts <= 200) return { hex: '#f44336', name: 'red' }
  return              { hex: '#8b1a1a',  name: 'dark-red' }
}

// ─────────────────────────────────────────────────────────────
// ALL SUPPORTED PROTOCOLS
// ─────────────────────────────────────────────────────────────
export const PROTOCOLS = [
  'DALI DT6',
  'DALI DT8',
  '0-10V',
  'PHASECUT',
  'ZIGBEE CCT',
  'WIFI CCT',
  'RF',
  'BLE',
  'ON/OFF',
]

// ─────────────────────────────────────────────────────────────
// FIXTURE DATABASE — 14 types
// ─────────────────────────────────────────────────────────────
export const fixtureDatabase = [
  {
    id: 'accent-spotlight',
    name: 'Accent Spotlight',
    category: 'Accent',
    symbol: '★',
    shape: 'star',
    wattages: [7, 12, 20, 35],
    beamAngles: [15, 25, 36, 50],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 100,
    cct: '3000K / 4000K',
  },
  {
    id: 'cob-downlight',
    name: 'COB Downlight',
    category: 'COB',
    symbol: '●',
    shape: 'circle',
    wattages: [7, 12, 18, 24, 36],
    beamAngles: [25, 36, 45, 60],
    supportedProtocols: ['DALI DT6', 'DALI DT8', '0-10V', 'PHASECUT', 'ZIGBEE CCT', 'WIFI CCT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 105,
    cct: '2700K / 3000K / 4000K / 5000K',
  },
  {
    id: 'track-light',
    name: 'Track Light',
    category: 'Track',
    symbol: '◆',
    shape: 'diamond',
    wattages: [15, 25, 35, 50],
    beamAngles: [15, 25, 36, 45, 60],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'RF', 'BLE', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 95,
    cct: '3000K / 4000K',
  },
  {
    id: 'panel-light',
    name: 'Panel Light',
    category: 'Panel',
    symbol: '▭',
    shape: 'rectangle',
    wattages: [18, 24, 36, 48],
    beamAngles: [120, 130, 140],
    supportedProtocols: ['DALI DT6', 'DALI DT8', '0-10V', 'PHASECUT', 'ZIGBEE CCT', 'WIFI CCT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 110,
    cct: '3000K / 4000K / 5000K',
  },
  {
    id: 'globe-omni',
    name: 'Globe / Omnidirectional',
    category: 'Globe',
    symbol: '◉',
    shape: 'circle-dot',
    wattages: [7, 9, 12],
    beamAngles: [270, 300, 360],
    supportedProtocols: ['DALI DT6', 'PHASECUT', 'ZIGBEE CCT', 'WIFI CCT', 'ON/OFF'],
    defaultProtocol: 'PHASECUT',
    lumensPerWatt: 85,
    cct: '2700K / 3000K',
  },
  {
    id: 'linear-fixture',
    name: 'Linear Fixture',
    category: 'Linear',
    symbol: '━',
    shape: 'line',
    wattages: [18, 24, 36, 50, 75],
    beamAngles: [60, 90, 120],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'RF', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 100,
    cct: '3000K / 4000K',
  },
  {
    id: 'wall-washer',
    name: 'Wall Washer',
    category: 'Washer',
    symbol: '◀',
    shape: 'triangle-left',
    wattages: [15, 24, 36],
    beamAngles: [30, 45, 60, 90],
    supportedProtocols: ['DALI DT6', 'DALI DT8', '0-10V', 'PHASECUT', 'RF', 'BLE', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 95,
    cct: '3000K / 4000K',
  },
  {
    id: 'floodlight',
    name: 'Floodlight',
    category: 'Flood',
    symbol: '◀▶',
    shape: 'double-arrow',
    wattages: [50, 100, 150, 200],
    beamAngles: [45, 60, 90, 120],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'RF', 'ZIGBEE CCT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 90,
    cct: '4000K / 5000K',
  },
  {
    id: 'landscape-spotlight',
    name: 'Landscape Spotlight',
    category: 'Landscape',
    symbol: '▲',
    shape: 'triangle-up',
    wattages: [7, 12, 20, 35],
    beamAngles: [12, 20, 36],
    supportedProtocols: ['DALI DT6', '0-10V', 'RF', 'BLE', 'ZIGBEE CCT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 90,
    cct: '3000K',
  },
  {
    id: 'path-bollard',
    name: 'Path / Bollard',
    category: 'Bollard',
    symbol: '▼',
    shape: 'triangle-down',
    wattages: [7, 12, 18],
    beamAngles: [60, 90, 120],
    supportedProtocols: ['0-10V', 'RF', 'BLE', 'ZIGBEE CCT', 'ON/OFF'],
    defaultProtocol: 'ON/OFF',
    lumensPerWatt: 80,
    cct: '3000K / 4000K',
  },
  {
    id: 'step-deck-light',
    name: 'Step / Deck Light',
    category: 'Step',
    symbol: '■',
    shape: 'small-square',
    wattages: [3, 5, 7],
    beamAngles: [60, 90, 120],
    supportedProtocols: ['0-10V', 'BLE', 'RF', 'ON/OFF'],
    defaultProtocol: 'ON/OFF',
    lumensPerWatt: 80,
    cct: '3000K',
  },
  {
    id: 'high-bay',
    name: 'High Bay',
    category: 'High Bay',
    symbol: '⬤',
    shape: 'big-circle',
    wattages: [100, 150, 200, 300],
    beamAngles: [60, 90, 120],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'RF', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 130,
    cct: '4000K / 5000K',
  },
  {
    id: 'street-light',
    name: 'Street Light',
    category: 'Street',
    symbol: '⊕',
    shape: 'circle-cross',
    wattages: [50, 100, 150, 200],
    beamAngles: [60, 90, 120],
    supportedProtocols: ['DALI DT6', '0-10V', 'PHASECUT', 'RF', 'ZIGBEE CCT', 'ON/OFF'],
    defaultProtocol: 'DALI DT6',
    lumensPerWatt: 120,
    cct: '4000K / 5000K',
  },
  {
    id: 'led-strip',
    name: 'LED Strip',
    category: 'Strip',
    symbol: '▬',
    shape: 'thick-line',
    wattages: null,                              // manual wattage input
    wattagePerMeter: [7, 9, 12, 14, 19, 24],   // W/m options to guide user
    beamAngles: [120, 160],
    supportedProtocols: ['DALI DT8', '0-10V', 'PHASECUT', 'ZIGBEE CCT', 'WIFI CCT', 'BLE', 'RF', 'ON/OFF'],
    defaultProtocol: 'DALI DT8',
    lumensPerWatt: 90,
    cct: '2700K – 6500K (tunable)',
  },
]
