/**
 * Content data for all /solutions/:slug pages.
 */

export const SOLUTION_DATA = {
  offices: {
    slug:      'offices',
    tag:       'SOLUTION',
    title:     'Office Lighting Design Software',
    subtitle:  'Design compliant office lighting to EN 12464-1 — 500 lux at the workplane, UGR ≤19, and DALI-ready for smart building integration.',
    seoTitle:  'Office Lighting Design Software — 500 Lux Compliance | Lumina Design',
    seoDesc:   'Design office lighting to EN 12464-1 (500 lux, UGR ≤19). Real-time lux calculations, DALI planning, and professional BOQ export. Free 14-day trial.',
    canonical: 'https://app.lightillumina.com/solutions/offices',
    luxTarget: 500,
    standard:  'EN 12464-1 Task Area',
    keySpec:   'UGR ≤ 19',
    intro: 'Open-plan offices, meeting rooms, private offices, and reception areas all have different lux requirements under EN 12464-1. Lumina lets you model each zone separately, verify compliance, and export the fixture schedule and DALI driver table your M&E contractor needs.',
    requirements: [
      { zone: 'Open plan workstations', lux: '500 lux', notes: 'EN 12464-1 clause 5.3' },
      { zone: 'Meeting rooms', lux: '500 lux', notes: 'EN 12464-1 clause 5.3' },
      { zone: 'Reception / lobby', lux: '300 lux', notes: 'EN 12464-1 clause 5.3' },
      { zone: 'Corridors / circulation', lux: '100 lux', notes: 'EN 12464-1 clause 5.3' },
      { zone: 'Server / IT rooms', lux: '500 lux', notes: 'EN 12464-1 clause 5.3' },
    ],
    workflow: [
      'Upload the office floor plan (PDF from AutoCAD or Revit)',
      'Draw each zone: open plan, meeting rooms, corridors',
      'Set lux target per zone (500 lux for task areas)',
      'Place LED panel fixtures from the library — AI recommender suggests quantity',
      'Enable DALI — assign addresses, define occupancy zones',
      'Export PDF report and Excel BOQ for the M&E contractor',
    ],
    fixtures: ['LED recessed panels (600×600, 1200×300)', 'Linear suspended luminaires', 'Downlights for corridors and breakout areas', 'Emergency maintained luminaires'],
  },

  warehouses: {
    slug:      'warehouses',
    tag:       'SOLUTION',
    title:     'Warehouse Lighting Design Software',
    subtitle:  'Calculate lux for high-bay and low-bay layouts. Meet NBC India 2016 and EN 12464-1 requirements for storage, picking, and loading areas.',
    seoTitle:  'Warehouse Lighting Design Software — High Bay Lux Calculation | Lumina Design',
    seoDesc:   'Design warehouse lighting with real-time lux calculations. Supports high-bay and low-bay layouts to NBC India 2016 and EN 12464-1. Free trial.',
    canonical: 'https://app.lightillumina.com/solutions/warehouses',
    luxTarget: 200,
    standard:  'NBC India 2016 / EN 12464-1',
    keySpec:   'High-bay support',
    intro: 'Warehouse lighting is driven by ceiling height, racking layout, and task type. A picking aisle needs 300 lux at 1m working height; bulk storage needs 100–200 lux. Lumina handles the geometry correctly — ceiling heights from 4m to 20m — and calculates lux at the working plane, not just the floor.',
    requirements: [
      { zone: 'General storage', lux: '100 lux', notes: 'NBC India 2016 / EN 12464-1' },
      { zone: 'Picking aisles', lux: '300 lux', notes: 'EN 12464-1 clause 5.4' },
      { zone: 'Loading / dispatch', lux: '300 lux', notes: 'EN 12464-1 clause 5.4' },
      { zone: 'Mezzanine offices', lux: '500 lux', notes: 'EN 12464-1 clause 5.3' },
      { zone: 'Emergency exit routes', lux: '1 lux min', notes: 'BS EN 1838' },
    ],
    workflow: [
      'Set ceiling height (high-bay: 8–20m, low-bay: 4–8m)',
      'Upload warehouse floor plan or draw blank canvas',
      'Divide into zones: storage, picking, loading, office',
      'Place LED high-bay or low-bay fixtures — AI recommends spacing',
      'Check lux compliance per zone, adjust fixture count',
      'Export fixture schedule and circuit allocation for electrical contractor',
    ],
    fixtures: ['LED high-bay (UFO) 100W–200W', 'LED linear high-bay 120W–240W', 'LED low-bay panels and battens', 'Emergency bulkhead luminaires'],
  },

  hospitals: {
    slug:      'hospitals',
    tag:       'SOLUTION',
    title:     'Hospital & Healthcare Lighting Design',
    subtitle:  'Meet demanding healthcare lux requirements — from 1,000 lux in operating theatres to 300 lux in wards — with zone-by-zone compliance checking.',
    seoTitle:  'Hospital Lighting Design Software — Healthcare Lux Standards | Lumina Design',
    seoDesc:   'Design hospital and healthcare lighting to EN 12464-1 and HTM 08-03. From operating theatres (1,000 lux) to wards (300 lux). Free 14-day trial.',
    canonical: 'https://app.lightillumina.com/solutions/hospitals',
    luxTarget: 1000,
    standard:  'EN 12464-1 / HTM 08-03',
    keySpec:   'Zone-by-zone compliance',
    intro: 'Healthcare facilities have the widest range of lux requirements of any building type — from 1,000 lux at the operating table to 50 lux in patient bedrooms at night. Lumina lets you model each clinical zone separately and verify compliance before the design is committed.',
    requirements: [
      { zone: 'Operating theatre (general)', lux: '1,000 lux', notes: 'EN 12464-1 / HTM 08-03' },
      { zone: 'Examination rooms', lux: '1,000 lux', notes: 'EN 12464-1' },
      { zone: 'Nurse stations', lux: '500 lux', notes: 'EN 12464-1' },
      { zone: 'Patient ward (general)', lux: '300 lux', notes: 'HTM 08-03' },
      { zone: 'Patient ward (reading)', lux: '300 lux', notes: 'HTM 08-03' },
      { zone: 'Corridors', lux: '200 lux', notes: 'EN 12464-1' },
    ],
    workflow: [
      'Upload hospital floor plan per department (floor by floor)',
      'Create zones for each clinical area with the appropriate lux target',
      'Place specialist fixtures: examination luminaires, clean-room rated panels',
      'Validate each zone meets its compliance threshold',
      'Add emergency maintained lighting across all egress routes',
      'Export per-department fixture schedule and circuit allocation',
    ],
    fixtures: ['Clean-room rated LED panels (IP54+)', 'Examination luminaires (colour-corrected, high CRI ≥90)', 'Corridor downlights with occupancy dimming', 'Emergency maintained luminaires (3-hour rated)'],
  },

  retail: {
    slug:      'retail',
    tag:       'SOLUTION',
    title:     'Retail Store Lighting Design',
    subtitle:  'Design accent and general lighting for retail spaces. High lux at displays, comfortable ambient, and DALI dimming for daylight-linked scenes.',
    seoTitle:  'Retail Lighting Design Software — Display & Ambient Lux Planning | Lumina Design',
    seoDesc:   'Design retail lighting with real-time lux calculations. Plan display accent lighting, general ambient, and DALI dimming zones. EN 12464-1 compliant. Free trial.',
    canonical: 'https://app.lightillumina.com/solutions/retail',
    luxTarget: 500,
    standard:  'EN 12464-1 Commercial',
    keySpec:   'Accent + ambient',
    intro: 'Retail lighting serves two purposes: ambient comfort for shoppers and accent lighting to make products stand out. EN 12464-1 sets a 500 lux floor for retail sales areas, but well-designed accent lighting often runs 1,500–3,000 lux at the display to achieve the contrast ratio that drives sales.',
    requirements: [
      { zone: 'Sales floor (general)', lux: '500 lux', notes: 'EN 12464-1 clause 5.24' },
      { zone: 'Display / feature areas', lux: '1,500–3,000 lux', notes: 'Design intent — accent' },
      { zone: 'Fitting rooms', lux: '500 lux', notes: 'EN 12464-1, high CRI ≥90' },
      { zone: 'Cash desk / POS', lux: '500 lux', notes: 'EN 12464-1' },
      { zone: 'Stock room', lux: '200 lux', notes: 'EN 12464-1' },
    ],
    workflow: [
      'Upload retail floor plan with fixture positions from concept design',
      'Separate zones: sales floor, display, fitting rooms, stockroom',
      'Place track-mounted spotlights for accent, recessed panels for ambient',
      'Set DALI zones: daylight-linked perimeter, feature display, general',
      'Check lux compliance and contrast ratios',
      'Export fixture schedule and DALI driver table for M&E contractor',
    ],
    fixtures: ['LED track spotlights (15°–24° beam)', 'Recessed LED downlights for ambient', 'Linear LED for shelf/perimeter lighting', 'LED panels for stockroom and BOH'],
  },

  classrooms: {
    slug:      'classrooms',
    tag:       'SOLUTION',
    title:     'Classroom Lighting Design for Indian Schools',
    subtitle:  'Design classroom lighting to NBC India 2016 standards — 300–500 lux at desk height with UGR ≤19 and no flicker for eye comfort.',
    seoTitle:  'Classroom Lighting Design Software — NBC India Standards | Lumina Design',
    seoDesc:   'Design school classroom lighting to NBC India 2016 (300–500 lux). Real-time lux calculation, UGR checking, and professional BOQ export. Free trial.',
    canonical: 'https://app.lightillumina.com/solutions/classrooms',
    luxTarget: 300,
    standard:  'NBC India 2016 Part 8',
    keySpec:   'UGR ≤ 19, flicker-free',
    intro: 'Classroom lighting in India is governed by NBC 2016 Part 8, which aligns broadly with EN 12464-1. Good classroom lighting reduces eye strain, improves concentration, and is particularly important in India where classrooms often have limited natural light due to deep floor plates or north-facing orientation.',
    requirements: [
      { zone: 'Classrooms (general)', lux: '300 lux', notes: 'NBC India 2016 Part 8' },
      { zone: 'Blackboard / whiteboard area', lux: '500 lux', notes: 'NBC India 2016 / EN 12464-1' },
      { zone: 'Art & craft rooms', lux: '500 lux', notes: 'EN 12464-1' },
      { zone: 'Computer labs', lux: '500 lux', notes: 'EN 12464-1 (screen glare consideration)' },
      { zone: 'Corridors / stairwells', lux: '100 lux', notes: 'NBC India 2016' },
    ],
    workflow: [
      'Upload school floor plan (typically 8m × 6m classroom)',
      'Set ceiling height (standard 3m, or 3.5m for newer buildings)',
      'Place LED batten fixtures or recessed panels — 300 lux target',
      'Add higher-lux zone at blackboard (500 lux with directional fittings)',
      'Check UGR ≤19 using fixture beam angle selection',
      'Export BOQ for school procurement with Indian brands (Havells, Wipro)',
    ],
    fixtures: ['LED batten luminaires 36W–40W (most common in Indian schools)', 'LED recessed panels 40W for new construction', 'LED spotlight for blackboard zone', 'Emergency bulkhead for corridors and stairwells'],
  },
}
